---
- hosts: all
  tasks:
  - shell: omd config demo set APACHE_MODE own
  - shell: omd config demo set MYSQL on
  - shell: omd config demo set THRUK_LOGCACHE on
  - shell: omd config demo set CORE off
  - shell: echo "testkey" > /omd/sites/demo/var/thruk/secret.key
  - file:
      path: /omd/sites/demo/var/thruk/secret.key
      mode: 0600
      owner: demo
      group: demo
  - copy:
      src: /root/thruk_local.conf
      dest: /omd/sites/demo/etc/thruk/thruk_local.conf
      owner: demo
      group: demo
